add slap-reproject to setup cfg
talmolab/sleap-anipose pull request #48
Opened 2024-06-12 20:01 UTC by ericleonardis

Running 'slap-reproject' resulted in an error where 'slap-reproject is not recognized as an internal or external command' which was identified in issue #46.  This was because the reproject_cli was not added to the setup.cfg file in the console_scripts entry points. I have added slap-reproject to that list and the file is now being created as expected.

2024-06-14 19:21 UTC, sean-afshar requested changes
Should it not be sleap_anipose:triangulation.reproject_cli instead of sleap_anipose.triangulate:reproject_cli?

2024-06-14 20:13 UTC, ericleonardis commented
Hey, sorry if I am missing something but it is already 'sleap_anipose:triangulation.reproject_cli' and not triangulate.

2024-06-14 20:23 UTC, ericleonardis commented
> Should it not be sleap_anipose:triangulation.reproject_cli instead of sleap_anipose.triangulate:reproject_cli?

whoops, sorry! very confused as to why it still generated the reprojections despite that error... but I fixed it now and it runs!

2024-06-15 03:40 UTC, sean-afshar reviewed
Looks good

2024-06-15 03:41 UTC, sean-afshar approved these changes

2024-06-15 03:41 UTC, merged